feat: Add web rendering of the TUI application (#1742)
* Initial version of the TUI app as a WASM32 web application

Renders the initial page but the navigation and auto-refresh are disabled

Made with AI

* Allow CORS only from localhost

* Enable more functionality for the Web TUI app

* WIP more cleanup, figuring out an event bus for web

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Fix fetching the scheduler state in WebTUI

Still WIP: there is an issue with RefCell<App> mutably borrowed

* Handle key press listening with AsyncAction indirection

The overcomes the problem with using mutable RefCell inside spawn_local()

* Do not try to use DateTime::now() in WASM32

Use 0/epoch as a fallback timestamp when parsing Prometheus samples in
WASM32

* Add ASFv2 license headers to Trunk.toml and index.html

* Fix clippy issues

* Use JavaScript Date.now() to get the current time for WebTUI

* Go back to "cli+tui" as default features

* Better feature gate for Config::new()

* Protect from inflight processing of tick events

* Better error handling for Terminal::restore()

* Run clippy per package/crate to have better control on the enabled features

* Do not scroll the page on ArrowDown/Up events

* Use CanvasBackend instead of DomBackend

This renders the TUI app in a <canvas> HTML element and it looks much
more like the terminal one.

* Use WebGl2Backend for even better rendering than CanvasBackend

* Render the Ballista logo in Web TUI

* Use light yellow + bold for the table's header names in Executors/Metrics

This makes it consistent with all other tables

* Simplify the config parsing for TUI/Web

In WebTUI we use only the default config, without loading files and env
vars

* Revert changes in executors/mod.rs

* Revert useless changes in jobs/mod.rs

* Revert useless changes in metrics/mod.rs

* Revert useless changes in main/mod.rs

* Revert useless changes in ui/mod.rs

* Imports cleanup - tui vs web

* Cleanup the async data loading for key events in the web-tui build

* Rename terminal module 'native' to 'tui'. For consistency

* Fail the build if both "tui" and "web" features are enabled in the same time

* Sort the dependencies for the WebTUI

* Enable "build-binary" feature for ballista-core.

Fixes a Clippy error:
```
error[E0432]: unresolved import `ballista_core::object_store`
  --> examples/examples/custom-client.rs:19:20
   |
19 | use ballista_core::object_store::state_with_s3_support;
   |                    ^^^^^^^^^^^^ could not find `object_store` in `ballista_core`
```

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Make it possible to register custom CORS allowed origins via env var

* Minor simplification

* Make it possible to allow more CORS methods. Allow all headers.

* Use RAII for resetting the tick_in_flight flag

* Prevent overflow for tick_ms setting

* More cleanup

* Quote the TRUNK_STAGING_DIR env var to support spaces in folder names

* Add a CI workflow that builds the Web TUI app

* Install wasm32-unknown-unknown target

* Build WebTUI app on MacOS

Github Actions is short for Ubuntu runners lately

* Do not create tarball for the uploaded webtui app

* Make it possible to load configuration from the query string

E.g. http://localhost:8080/?ballista_scheduler_url=http://localhost:50050&ballista_tick_interval=3000&ballista_http_timeout=3000&ballista_job_stage_plan_tree=true

* remove unused import

* Improve the structures of the tui vs web modules

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Fix all Clippy issues in the web part of TUI

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Immediately show the initially loaded data

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>

* Add more docs to Trunk.toml and wasm.rs

---------

Signed-off-by: Martin Tzvetanov Grigorov <mgrigorov@apache.org>