Add missing limit to tpch queries
This fixes tests that failed with mismatched record count; for example,

```
thread 'tests::q2' panicked at benchmarks/src/bin/tpch.rs:1026:5:
assertion `left == right` failed
  left: 100
 right: 460
```

The limits was not in the offical sql query but set through instructions
at the end of the sql file with ":n 100". For example, the query-2 from
the offical TPCH dbgen folder is as follows:

```sql
:x
:o
select
	s_acctbal,
	s_name,
	n_name,
	p_partkey,
	p_mfgr,
	s_address,
	s_phone,
	s_comment
from
	part,
	supplier,
	partsupp,
	nation,
	region
where
	p_partkey = ps_partkey
	and s_suppkey = ps_suppkey
	and p_size = :1
	and p_type like '%:2'
	and s_nationkey = n_nationkey
	and n_regionkey = r_regionkey
	and r_name = ':3'
	and ps_supplycost = (
		select
			min(ps_supplycost)
		from
			partsupp,
			supplier,
			nation,
			region
		where
			p_partkey = ps_partkey
			and s_suppkey = ps_suppkey
			and s_nationkey = n_nationkey
			and n_regionkey = r_regionkey
			and r_name = ':3'
	)
order by
	s_acctbal desc,
	n_name,
	s_name,
	p_partkey;
:n 100
```